# Deploy pipeline
# https://aka.ms/yaml

trigger: none

variables:
- group: TeamVars.TEMPLATE - Android

pool:
  name: 'Private Pool Mobile'
  demands:
    - Agent.OS -equals Linux

jobs:
  - job: BundleReleaseJob
    displayName: Bundle Release
    # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    steps:
    - task: DownloadSecureFile@1
      name: googlePlayServices
      displayName: 'Download Google play services file'
      inputs:
        secureFile: 'template-android-release-google-services.json'

    - bash: |
        cd app/src/
        mkdir release
      displayName: 'Create build Directory'

    - bash: 'mv $(googlePlayServices.secureFilePath) ./app/src/release/google-services.json'
      displayName: 'Copy Google play services file into project'

    - task: DownloadSecureFile@1
      name: releaseKeystore
      displayName: 'Download Keystore to upload to Google Play'
      inputs:
        secureFile: 'TEMPLATE-google-play-upload.keystore'
    - task: DownloadSecureFile@1
      name: serviceAccountJson
      displayName: 'Download Service Account key to upload to Google Play'
      inputs:
        secureFile: 'TEMPLATE-service-account-google-play.json'
    - bash: |
        ./gradlew bundleRelease
        keytool -printcert -jarfile app/build/outputs/bundle/release/app-release.aab
      displayName: Bundle Release
      env:
        KEY_STORE_PATH: $(releaseKeystore.secureFilePath)
        RELEASE_STORE_PASSWORD: $(RELEASE_KEY_PASSWORD)
        RELEASE_KEY_ALIAS: $(RELEASE_KEY_ALIAS)
        RELEASE_KEY_PASSWORD: $(RELEASE_KEY_PASSWORD)
        BUILDER_USER: $(BUILDER_USER)
        BUILDER_PASSWORD: $(BUILDER_PASSWORD)

    - bash: |
        ruby --version
        gem install bundler
        bundle install
        bundle exec fastlane run validate_play_store_json_key json_key:$(serviceAccountJson.secureFilePath)
      displayName: Validate Service Account
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: "app/build/outputs"
        artifactName: Release-Bundle
      displayName: Publish Artifacts
    - bash: |
        bundle exec fastlane deploy
      displayName: Publish to Play Store Internal Track
      env:
        SECURE_FILE_PATH: $(serviceAccountJson.secureFilePath)


