# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV['SUPPLY_UPLOAD_MAX_RETRIES']='5'

default_platform(:android)

ENV['SUPPLY_UPLOAD_MAX_RETRIES']='5'

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      root_url: "https://androidpublisher.googleapis.com/",
      skip_upload_images: false,
      skip_upload_screenshots: false,
      aab: "app/build/outputs/bundle/release/app-release.aab",
      track: "internal",
      release_status: "draft",
      json_key: ENV["SECURE_FILE_PATH"]
    )
  end
end
